routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VoluntarioController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::resource('voluntarios', VoluntarioController::class);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Models/Voluntario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Voluntario extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'nome', 'email', 'cpf'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/VoluntarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Voluntario;
use Illuminate\Http\Request;

class VoluntarioController extends Controller
{

    public function index()
    {
        $voluntarios = Voluntario::all();

        return view('voluntarios.index', compact('voluntarios'));
    }

    public function create()
    {
        return view('voluntarios.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nome' => 'required',
            'cpf' => 'required',
            'email' => 'required',
        ]);

        Voluntario::create($request->all());

        return redirect()->route('voluntarios.create')->with('mensagem', 'Voluntario cadastrado com SUCESSO!!');
    }


    public function show(Voluntario $voluntario)
    {
        return view('voluntarios.show', compact('voluntario'));
    }


    public function edit(Voluntario $voluntario)
    {
        return view('voluntarios.edit', compact('voluntario'));
    }


    public function update(Request $request, Voluntario $voluntario)
    {
        $request->validate([
            'nome' => 'required',
            'email' => 'required',
            'cpf' => 'required',
        ]);
        
        $voluntario->update($request->all());

        return redirect()->route('voluntarios.index')->with('mensagem', 'Voluntario atualizado com Sucesso');
    }

    public function destroy(Voluntario $voluntario)
    {
        $voluntario->delete();

        return redirect()->route('voluntarios.index')->with('mensagem', 'Voluntario Excluido com Sucesso');
    }
}

resources/views/voluntarios/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cadastro</title>
</head>
<body>
    <h1>Novo Livro</h1>
 
@if($status = Session::get('mensagem'))
  <h2>{{ $status }}</h2>
@endif
 
@if($errors->any())
  <h2>Houve alguns erros ao processar o formulário</h2>
  <ul>
     @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
     @endforeach
  </ul>
@endif
 
<form action="{{ route('voluntarios.store') }}" method="post">
@csrf
<table width="200" border="0" cellspacing="3" 
  cellpadding="3">
  <tr>
    <td>Nome:</td>
    <td><input type="text" name="nome" id="nome" 
      placeholder="Nome"></td>
  </tr>
  <tr>
    <td>Email:</td>
    <td><input type="text" name="email" id="email"
      placeholder="E-mail"></td>
  </tr>
  <tr>
    <td>CPF:</td>
    <td><input type="text" size="10" name="cpf" 
      id="cpf" placeholder="CPF"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><button type="submit">Cadastrar</button></td>
  </tr>
</table>
</form>

</body>
</html>

resources/views/voluntarios/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h1>Atualizar Voluntario</h1>

@if($errors->any())
  <h2>Houve alguns erros ao processar o formulário</h2>
  <ul>
     @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
     @endforeach
  </ul>
@endif

<form action="{{ route('voluntarios.update', $voluntario->id) }}" method="post">
@csrf
@method('PUT')

<table width="200" border="0" cellspacing="3" cellpadding="3">
  <tr>
    <td>Título:</td>
    <td><input type="text" value="{{ $voluntario->nome }}" 
      name="nome" id="nome" placeholder="nome"></td>
  </tr>
  <tr>
    <td>Autor:</td>
    <td><input type="text" value="{{ $voluntario->email }}" 
      name="email" id="email" placeholder="email"></td>
  </tr>
  <tr>
    <td>Páginas</td>
    <td><input type="text" value="{{ $voluntario->cpf }}" 
      size="10" name="cpf" id="cpf" 
      placeholder="cpf"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><button type="submit">Salvar Alterações</button></td>
  </tr>
</table>

</body>
</html>

resources/views/voluntarios/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>voluntarios</title>
</head>

<body>
    <h1>voluntarios Cadastrados</h1>

@if($status = Session::get('mensagem'))
  <h2>{{ $status }}</h2>
@endif

<h4><a href="{{ route('voluntarios.create') }}">Cadastrar 
  Novo Livro</a></h4>

<table width="709" border="1" cellspacing="0" cellpadding="3">
  <tr>
    <td width="85" align="center"><strong>Id</strong></td>
    <td width="161" align="center"><strong>Nome</strong></td>
    <td width="156" align="center"><strong>E-mail</strong></td>
    <td width="98" align="center"><strong>CPF</strong></td>
    <td width="167" align="center"><strong>Opções</strong></td>
  </tr>
  
  @foreach($voluntarios as $voluntario)
  
  <tr>
      <td align="center">{{ $voluntario->id }}</td>
      <td>{{ $voluntario->nome }}</td>
      <td>{{ $voluntario->email }}</td>
      <td align="center">{{ $voluntario->cpf }}</td>
      <td align="center">
      
      <form action="{{ route('voluntarios.destroy', $voluntario->id) }}" 
         method="post">
         <a href="{{ route('voluntarios.show', 
           $voluntario->id) }}">Detalhes</a> | 
           <a href="{{ route('voluntarios.edit', 
           $voluntario->id) }}">Editar</a>
      
         @csrf
         @method('DELETE')
      
         <button type="submit">Excluir</button>
      </form>
      
    </tr>
  @endforeach
  
</table>


</body>
</html>

resources/views/voluntarios/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <h1>Detalhes do Voluntario</h1>

    <table width="500" border="1" cellspacing="0" cellpadding="3">
        <tr>
          <td><strong>Id</strong></td>
          <td>{{ $voluntario->id }}</td>
        </tr>
        <tr>
          <td><strong>Nome</strong></td>
          <td> {{ $voluntario->nome }}</td>
        </tr>
        <tr>
          <td><strong>E-mail</strong></td>
          <td>{{ $voluntario->email }}</td>
        </tr>
        <tr>
          <td><strong>CPF</strong></td>
          <td>{{ $voluntario->cpf }}</td>
        </tr>
      </table>

</body>
</html>